language: node_js
node_js:
  - 'stable'

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install

script:
  - CI=false npm run build

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; firebase deploy --token $FIREBASE_TOKEN --non-interactive; else echo "PR skip deploy"; fi

notifications:
  email:
    on_failure: change
    on_success: change