language: node_js
node_js:
  - 'stable'

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - npm install

script:
  - CI=false npm run build

before_deploy:
  - npm install -g firebase-tools
  - chmod +x deploy.sh

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  only: 'hosting'
  edge: true

notifications:
  email:
    on_failure: change
    on_success: change