language: node_js
node_js:
  - 'stable'

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - chmod +x deploy.sh

before_script:
  - npm install -g firebase-tools
  - npm install

script:
  - CI=false npm run build

after_success:
  - ./deploy.sh

notifications:
  email:
    on_failure: change
    on_success: change