language: node_js
node_js:
  - stable

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - develop

before_script:
  - npm install

script:
  - CI=false npm run build

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
  only: 'hosting'
  edge: true
  on:
    branch:
      - master
      - develop

notifications:
  email:
    on_failure: change
    on_success: change