language: node_js
node_js:
  - 'stable'

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - develop

before_script:
  - npm install

script:
  - CI=false npm run build

before_deploy:
  - npm install -g firebase-tools
  - chmod +x deploy.sh

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN_DEV
  project: $FIREBASE_PROJECT_DEV
  only: 'hosting'
  edge: true
  on:
    branch: develop
  provider: firebase
  token: $FIREBASE_TOKEN_PROD
  project: $FIREBASE_PROJECT_PROD
  only: 'hosting'
  edge: true
  on:
    branch: master


notifications:
  email:
    on_failure: change
    on_success: change