on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
name: Sonar Analysis
jobs:
  sonarcloud:
    name: Sonarcloud Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: fix code coverage paths
        run: |
          sed -i 's/\/home\/runner\/work\/march-madness-calcutta\/march-madness-calcutta\//\/github\/workspace\//g' /github/workspace/coverage/lcov.info
          sed -i 's/\/home\/runner\/work\/march-madness-calcutta\/march-madness-calcutta\//\/github\/workspace\//g' /github/workspace/test-report.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}