on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
name: Sonar Analysis
jobs:
  sonarcloud:
    name: Sonarcloud Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          # projectBaseDir: /home/runner/work/march-madness-calcutta/march-madness-calcutta/src
          args: >
            -Dsonar.organization=burkcules
            -Dsonar.projectKey=burke1791_march-madness-calcutta
            -Dsonar.sources=.
            -Dsonar.exclusions=./src/**/__tests__/*.test.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}