on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
name: Sonar Analysis
jobs:
  unit_tests:
    name: Unit Tests and Code Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: echo dir
        run: pwd
  sonarcloud:
    name: Sonarcloud Analysis
    needs: unit_tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: src
        args: >
          -Dsonar.organization=my-burkcules
          -Dsonar.projectKey=burke1791_march-madness-calcutta
          -Dsonar.javascript.lcov.reportPaths=../coverage/lcov.info
          -Dsonar.test.exclusions=**/__tests__/*.test.js
          -Dsonar.tests=**/__tests__/*.test.js
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}