
name: Stage

on:
  push:
    branches: develop

jobs:
  build_and_deploy:
    name: Deploy to firebase hosting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: CI=false npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: $FIREBASE_SERVICE_ACCOUNT
          projectId: $FIREBASE_PROJECT_ID_DEV

  
env:
  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEV }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_DEV }}