
name: Stage

on:
  push:
    branches: stage

jobs:
  build_and_deploy:
    name: Deploy to firebase hosting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g firebase-tools
      - run: npm install
      - run: CI=false npm run build
      - run: |
          firebase use --add $FIREBASE_PROJECT_ID
          firebase deploy --only hosting --token $FIREBASE_TOKEN

  
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_DEV }}
  REACT_APP_BUILD_ENV: dev
